<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Obat-obatan
            [
                'name' => 'Paracetamol 500mg',
                'sku' => 'MED-001',
                'description' => 'Obat pereda nyeri dan penurun demam. Aman untuk dewasa dan anak di atas 6 tahun. Dikonsumsi setelah makan.',
                'category' => 'medicine',
                'price' => 12500,
                'cost_price' => 8000,
                'stock' => 850,
                'min_stock' => 100,
                'unit' => 'strip',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Kimia Farma',
                'expiry_date' => now()->addYears(2),
            ],
            [
                'name' => 'Amoxicillin 500mg',
                'sku' => 'MED-002',
                'description' => 'Antibiotik spektrum luas untuk infeksi bakteri. Harus dengan resep dokter. Kapsul 500mg.',
                'category' => 'medicine',
                'price' => 35000,
                'cost_price' => 22000,
                'stock' => 420,
                'min_stock' => 50,
                'unit' => 'strip',
                'is_active' => true,
                'requires_prescription' => true,
                'manufacturer' => 'Sanbe Farma',
                'expiry_date' => now()->addMonths(18),
            ],
            [
                'name' => 'Omeprazole 20mg',
                'sku' => 'MED-003',
                'description' => 'Obat untuk mengatasi maag dan GERD. Diminum sebelum makan pagi.',
                'category' => 'medicine',
                'price' => 28000,
                'cost_price' => 18000,
                'stock' => 380,
                'min_stock' => 40,
                'unit' => 'strip',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Dexa Medica',
                'expiry_date' => now()->addYears(2),
            ],
            [
                'name' => 'Cetirizine 10mg',
                'sku' => 'MED-004',
                'description' => 'Antihistamin untuk alergi, gatal-gatal, dan pilek. Tidak menyebabkan kantuk berat.',
                'category' => 'medicine',
                'price' => 15000,
                'cost_price' => 9500,
                'stock' => 520,
                'min_stock' => 60,
                'unit' => 'strip',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Kalbe Farma',
                'expiry_date' => now()->addYears(2),
            ],
            [
                'name' => 'Ibuprofen 400mg',
                'sku' => 'MED-005',
                'description' => 'Anti-inflamasi non-steroid untuk nyeri dan peradangan. Diminum setelah makan.',
                'category' => 'medicine',
                'price' => 18000,
                'cost_price' => 11000,
                'stock' => 290,
                'min_stock' => 40,
                'unit' => 'strip',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Tempo Scan',
                'expiry_date' => now()->addMonths(20),
            ],
            
            // Suplemen
            [
                'name' => 'Vitamin C 1000mg',
                'sku' => 'SUP-001',
                'description' => 'Suplemen vitamin C dosis tinggi untuk meningkatkan daya tahan tubuh. Tablet effervescent rasa jeruk.',
                'category' => 'supplement',
                'price' => 45000,
                'cost_price' => 28000,
                'stock' => 680,
                'min_stock' => 80,
                'unit' => 'tube',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Bayer',
                'expiry_date' => now()->addYears(3),
            ],
            [
                'name' => 'Multivitamin Dewasa',
                'sku' => 'SUP-002',
                'description' => 'Kombinasi vitamin dan mineral lengkap untuk kesehatan optimal. 1 tablet per hari.',
                'category' => 'supplement',
                'price' => 125000,
                'cost_price' => 85000,
                'stock' => 320,
                'min_stock' => 30,
                'unit' => 'botol',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Blackmores',
                'expiry_date' => now()->addYears(2),
            ],
            [
                'name' => 'Omega 3 Fish Oil',
                'sku' => 'SUP-003',
                'description' => 'Minyak ikan kaya omega-3 untuk kesehatan jantung dan otak. Soft capsule mudah ditelan.',
                'category' => 'supplement',
                'price' => 185000,
                'cost_price' => 120000,
                'stock' => 150,
                'min_stock' => 20,
                'unit' => 'botol',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Nature\'s Way',
                'expiry_date' => now()->addYears(2),
            ],
            [
                'name' => 'Vitamin D3 1000 IU',
                'sku' => 'SUP-004',
                'description' => 'Suplemen vitamin D untuk kesehatan tulang dan sistem imun.',
                'category' => 'supplement',
                'price' => 95000,
                'cost_price' => 62000,
                'stock' => 240,
                'min_stock' => 25,
                'unit' => 'botol',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Wellness',
                'expiry_date' => now()->addYears(3),
            ],
            [
                'name' => 'Kalsium + Vitamin D',
                'sku' => 'SUP-005',
                'description' => 'Kombinasi kalsium dan vitamin D untuk tulang kuat. Ideal untuk wanita dan lansia.',
                'category' => 'supplement',
                'price' => 145000,
                'cost_price' => 95000,
                'stock' => 180,
                'min_stock' => 20,
                'unit' => 'botol',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'CDR',
                'expiry_date' => now()->addYears(2),
            ],
            
            // Alat Kesehatan
            [
                'name' => 'Tensimeter Digital',
                'sku' => 'DEV-001',
                'description' => 'Alat ukur tekanan darah digital otomatis dengan layar LCD besar. Memori hingga 60 hasil.',
                'category' => 'medical_device',
                'price' => 385000,
                'cost_price' => 250000,
                'stock' => 45,
                'min_stock' => 10,
                'unit' => 'unit',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Omron',
                'expiry_date' => null,
            ],
            [
                'name' => 'Termometer Digital',
                'sku' => 'DEV-002',
                'description' => 'Termometer digital cepat dan akurat. Hasil dalam 10 detik. Anti air.',
                'category' => 'medical_device',
                'price' => 75000,
                'cost_price' => 45000,
                'stock' => 120,
                'min_stock' => 20,
                'unit' => 'unit',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Beurer',
                'expiry_date' => null,
            ],
            [
                'name' => 'Pulse Oximeter',
                'sku' => 'DEV-003',
                'description' => 'Alat ukur saturasi oksigen dan detak jantung. Portabel dengan layar OLED.',
                'category' => 'medical_device',
                'price' => 195000,
                'cost_price' => 125000,
                'stock' => 85,
                'min_stock' => 15,
                'unit' => 'unit',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Yuwell',
                'expiry_date' => null,
            ],
            [
                'name' => 'Glucometer Set',
                'sku' => 'DEV-004',
                'description' => 'Alat cek gula darah lengkap dengan lancing device dan 25 strip test.',
                'category' => 'medical_device',
                'price' => 285000,
                'cost_price' => 180000,
                'stock' => 35,
                'min_stock' => 8,
                'unit' => 'set',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Accu-Chek',
                'expiry_date' => null,
            ],
            [
                'name' => 'Nebulizer Kompressor',
                'sku' => 'DEV-005',
                'description' => 'Alat inhalasi untuk pengobatan asma dan penyakit pernapasan. Efisien dan mudah digunakan.',
                'category' => 'medical_device',
                'price' => 485000,
                'cost_price' => 320000,
                'stock' => 25,
                'min_stock' => 5,
                'unit' => 'unit',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Philips',
                'expiry_date' => null,
            ],
            
            // Personal Care
            [
                'name' => 'Hand Sanitizer 500ml',
                'sku' => 'PC-001',
                'description' => 'Gel antiseptik tangan dengan alkohol 70%. Membunuh 99.9% kuman.',
                'category' => 'personal_care',
                'price' => 45000,
                'cost_price' => 28000,
                'stock' => 450,
                'min_stock' => 50,
                'unit' => 'botol',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Antis',
                'expiry_date' => now()->addYears(3),
            ],
            [
                'name' => 'Masker Medis 3 Ply (50pcs)',
                'sku' => 'PC-002',
                'description' => 'Masker medis 3 lapis dengan filter efektif. Earloop elastis nyaman.',
                'category' => 'personal_care',
                'price' => 65000,
                'cost_price' => 42000,
                'stock' => 580,
                'min_stock' => 100,
                'unit' => 'box',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Sensi',
                'expiry_date' => now()->addYears(5),
            ],
            [
                'name' => 'Alkohol 70% 100ml',
                'sku' => 'PC-003',
                'description' => 'Alkohol antiseptik untuk desinfeksi luka dan permukaan. Cepat menguap.',
                'category' => 'personal_care',
                'price' => 18000,
                'cost_price' => 10000,
                'stock' => 320,
                'min_stock' => 40,
                'unit' => 'botol',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'OneMed',
                'expiry_date' => now()->addYears(3),
            ],
            
            // P3K
            [
                'name' => 'Kotak P3K Lengkap',
                'sku' => 'FA-001',
                'description' => 'Kotak P3K berisi perban, plester, kapas, antiseptik, dan perlengkapan darurat lainnya.',
                'category' => 'first_aid',
                'price' => 185000,
                'cost_price' => 120000,
                'stock' => 65,
                'min_stock' => 15,
                'unit' => 'set',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'General Care',
                'expiry_date' => now()->addYears(3),
            ],
            [
                'name' => 'Perban Elastis 10cm',
                'sku' => 'FA-002',
                'description' => 'Perban elastis untuk balut luka dan kompresi. Panjang 4.5 meter.',
                'category' => 'first_aid',
                'price' => 25000,
                'cost_price' => 15000,
                'stock' => 180,
                'min_stock' => 30,
                'unit' => 'roll',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'OneMed',
                'expiry_date' => now()->addYears(5),
            ],
            [
                'name' => 'Plester Luka Waterproof',
                'sku' => 'FA-003',
                'description' => 'Plester luka tahan air dengan bantalan antiseptik. Isi 100 lembar berbagai ukuran.',
                'category' => 'first_aid',
                'price' => 55000,
                'cost_price' => 35000,
                'stock' => 220,
                'min_stock' => 25,
                'unit' => 'box',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Hansaplast',
                'expiry_date' => now()->addYears(4),
            ],
            [
                'name' => 'Betadine Solution 30ml',
                'sku' => 'FA-004',
                'description' => 'Larutan antiseptik povidone iodine untuk membersihkan dan mencegah infeksi luka.',
                'category' => 'first_aid',
                'price' => 32000,
                'cost_price' => 20000,
                'stock' => 280,
                'min_stock' => 35,
                'unit' => 'botol',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Betadine',
                'expiry_date' => now()->addYears(3),
            ],
            
            // Baby Care
            [
                'name' => 'Minyak Telon Plus',
                'sku' => 'BB-001',
                'description' => 'Minyak telon dengan penolak nyamuk alami. Aman untuk bayi baru lahir.',
                'category' => 'baby_care',
                'price' => 38000,
                'cost_price' => 24000,
                'stock' => 195,
                'min_stock' => 25,
                'unit' => 'botol',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Cap Lang',
                'expiry_date' => now()->addYears(3),
            ],
            [
                'name' => 'Popok Bayi Size M (48pcs)',
                'sku' => 'BB-002',
                'description' => 'Popok bayi premium daya serap tinggi. Lembut di kulit dan anti bocor.',
                'category' => 'baby_care',
                'price' => 125000,
                'cost_price' => 85000,
                'stock' => 145,
                'min_stock' => 20,
                'unit' => 'pack',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Pampers',
                'expiry_date' => null,
            ],
            [
                'name' => 'Baby Lotion 200ml',
                'sku' => 'BB-003',
                'description' => 'Lotion bayi lembut untuk melembabkan kulit. Formula hypoallergenic.',
                'category' => 'baby_care',
                'price' => 48000,
                'cost_price' => 30000,
                'stock' => 165,
                'min_stock' => 20,
                'unit' => 'botol',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Johnson\'s',
                'expiry_date' => now()->addYears(3),
            ],
            
            // Skincare
            [
                'name' => 'Sunscreen SPF 50+',
                'sku' => 'SK-001',
                'description' => 'Tabir surya SPF 50+ PA++++ untuk perlindungan maksimal dari sinar UV.',
                'category' => 'skincare',
                'price' => 165000,
                'cost_price' => 105000,
                'stock' => 92,
                'min_stock' => 15,
                'unit' => 'tube',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Wardah',
                'expiry_date' => now()->addYears(2),
            ],
            [
                'name' => 'Pelembab Wajah Hyaluronic',
                'sku' => 'SK-002',
                'description' => 'Pelembab dengan hyaluronic acid untuk kulit terhidrasi maksimal.',
                'category' => 'skincare',
                'price' => 195000,
                'cost_price' => 130000,
                'stock' => 78,
                'min_stock' => 12,
                'unit' => 'jar',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Somethinc',
                'expiry_date' => now()->addYears(2),
            ],
            [
                'name' => 'Facial Wash Gentle',
                'sku' => 'SK-003',
                'description' => 'Sabun cuci muka lembut untuk semua jenis kulit. pH balanced.',
                'category' => 'skincare',
                'price' => 85000,
                'cost_price' => 55000,
                'stock' => 135,
                'min_stock' => 18,
                'unit' => 'tube',
                'is_active' => true,
                'requires_prescription' => false,
                'manufacturer' => 'Cetaphil',
                'expiry_date' => now()->addYears(3),
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
